config/routes.rb
Haiyantour::Application.routes.draw do
  resources :subscribers, only: :create
  resources :contacts, only: :create
  get "story" => "pages#story"
  get "news" => "pages#news"
  get "media" => "pages#media"
  get "discovery" => "pages#discovery"
  get "contact" => "pages#contact"

  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :telephone, presence: true
	validates :content, presence: true
end

app/models/contacts.rb
class Contacts < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :telephone, presence: true
	validates :kind, presence: true
	validates :heard_about_us, presence: true
	validates :content, presence: true
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
	validates :email_address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)

    # TODO: trigger the mailer to send email to both contact and admin
    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url, notice: 'Thank you for submitting your letter. We will contact you shortly.' }
      else
        format.html { redirect_to root_url, notice: 'Had an issue for submitting!' }
      end
    end
  end

    # TODO: check the cases of different inputs parameters 
    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :telephone, :company, :kind, :content, :heard_about_us)
    end
end

app/controllers/pages_controller.rb
require 'net/http'
require 'json'

class PagesController < ApplicationController
  helper_method :weather, :weibo
  YAHOO_ROOT = "http://query.yahooapis.com/v1/public/yql"
  WEIBO_ROOT = "https://api.weibo.com/2/friendships/groups/timeline.json"
  
  def weather
    url = YAHOO_ROOT + "?q=select%20*%20from%20weather.forecast%20"
    url += "where%20woeid%3D2131595%20and%20u%3D'c'&format=json"
    doc = get_response_yahoo url
    doc
  end

  def get_response_yahoo url
    begin
      response = Net::HTTP.get_response(URI.parse url).body.to_s
    rescue => e
      raise "Failed to get weather [url=#{url}, e=#{e}]."
    end

    response = JSON.parse(response)
    if response.nil?
      raise "Failed to get weather [url=#{url}]."
    end
    result = response["query"]["results"]["channel"]["item"]["description"]
    result
  end

  def weibo
    url = WEIBO_ROOT + "?source=1981538069&access_token=2.00mOABwB8Z1GKC817772b5f9owdscC&list_id=3657627672388520&count=2"
    doc = get_response_weibo url
    doc
  end

  def get_response_weibo url
    begin
      response = Net::HTTP.get_response(URI.parse url).body.to_s
    rescue => e
      raise "Failed to get weather [url=#{url}, e=#{e}]."
    end

    response = JSON.parse(response)
    if response.nil?
      raise "Failed to get weather [url=#{url}]."
    end
    first = feed_generator response["statuses"][0]
    second = feed_generator response["statuses"][1]
    # third = feed_generator response["statuses"][2]
    # result = "<ul><li><p> " + first + " </p></li>" + "<li><p> " + second + " </p></li>" + "<li><p> " + third + " </p></li></ul>"
    result = "<ul><li><p> " + first + " </p></li>" + "<li><p> " + second + " </p></li></ul>"
  end

  def feed_generator raw
    date = raw["created_at"].split(" ")[0..2].join(" ")
    time = raw["created_at"].split(" ")[3].split(":")[0,2].join(":")
    puts "DATETIME ______________________________ "
    puts date
    puts time
    datetime = date + " " + time
    feed = nil
    if raw.include?("retweeted_status")
      feed = raw["text"] + " -- [转发微博] -- " +  raw["retweeted_status"]["text"] + "<span> " + datetime + "</span>"
    else
      feed = raw["text"] + "<span> " + datetime + "</span>"
    end
    feed
  end
  
  def home
  end

  def story
  end

  def news
  end

  def media
  end

  def discovery
  end

  def contact
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to root_url, notice: 'Thanks for keeping up to date with us!' }
      else
        format.html { redirect_to root_url, notice: 'Had an issue for subscribing!' }
      end
    end
  end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:email_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Haiyantour</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
	  <%= stylesheet_link_tag "home.css" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div id="cssmenu">
			<ul>
				<li><%= link_to "CONTACT US", contact_url %></li>
				<li class="has-sub"><%= link_to "DISCOVERY", discovery_url %>
					<ul>
						<li><%= link_to "FOOD", discovery_url %></li>
						<li><%= link_to "HOTEL", discovery_url %></li>
						<li><%= link_to "COUNTIES", discovery_url %></li>
						<li><%= link_to "TRANSIT", discovery_url %></li>
						<li class="last"><%= link_to "BUSINESS", discovery_url %></li>
					</ul>
				</li>
				<li><%= link_to "MEDIA", media_url %></li>
				<li><%= link_to "NEWS", news_url %></li>
				<li><%= link_to "STORY", story_url %></li>
				<li><%= link_to "HOME", root_url %></li>	
			</ul>
		</div>
		<%= yield %>
		<!-- Footer -->
		<div id="footer">
			<div class="inner">
				<div class="container">
					<div class="column social">
						<a href="localhost:3000/contact/">
							<h3>Contact Us</h3>
						</a>
						<p>
							<a>+86-573-86039910</a>
						</p>
						<h3>Follow Us</h3>
						<p>
							<span class="social-media-icons-round-footer">
								<a href="http://www.weibo.com/haiyantourism" class="social-icon-round-footer weibo"></a>
								<a href="http://www.wechat.com" class="social-icon-round-footer wechat"></a>
								<a href="http://www.facebook.com" class="social-icon-round-footer facebook"></a>
							</span>
						</p>
					</div>
					<div class="column sitemap">
						<h3>Site Map</h3>
						<p>
							<%= link_to  "News", news_url %>
						</p>
						<p>
							<%= link_to "Media", media_url %>
						</p>
						<p>
							<%= link_to "Discovery", discovery_url %>
						</p>
					</div>
					<div class="column find">
						<h3>Find Us</h3>
							<p>
								<a class="location" href="http://map.baidu.com/?newmap=1&s=inf%26uid%3D7f243a72c8dcd326d3f49e57%26c%3D2491%26all%3D1%26wd%3D%E6%B5%99%E6%B1%9F%E6%B5%B7%E7%9B%90%E8%A1%97%E9%81%93%E6%96%B0%E6%A1%A5%E5%8C%97%E8%B7%AF180%E5%8F%B7&fr=alam1&ext=1&from=alamap" target="_blank">Haiyan Office</a>
							</p>
					</div>
					<div class="column subscriber">
						<h3>HYTOUR Newsletter</h3>
						<p>Interested in Haiyan Tour updates?</p>
						<%= form_for(Subscriber.new) do |f| %>
							<% if flash[:notice] %>
	  						<p class="notice"><%= flash[:notice] %></p>
							<% end %>
							<div>
								<%= f.text_field :email_address, class: "subscribeInputField", placeholder: "Email Address" %>
							</div>
							<div>
								<%= f.submit "Subscribe", class: "subscribeButton"%>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/pages/contact.html.erb
<head>
	<%= stylesheet_link_tag "contacts.css" %>
</head>
<body>
	<div class="form-container">
		<div class="form-main">
			<%= form_for Contact.new, :url => url_for(:controller => "contacts", :action => "create"), html: {class:"cbp-mc-form"} do |f| %>
				<div class="cbp-mc-column">
					<%= f.label :first_name %>
					<%= f.text_field :first_name %>
					<%= f.label :last_name %>
					<%= f.text_field :last_name %>
					<%= f.label :email %>
					<%= f.text_field :email %>
					<%= f.label :telephone %>
					<%= f.text_field :telephone %>
					<%= f.label :company %>
					<%= f.text_field :company %>
				</div>
				<div class="cbp-mc-column">
					<%= f.label :kind %>
					<%= f.select :kind, ["", "Complaint", "Consultant", "Suggestion"], {} %>
					<%= f.label :heard_about_us %>
					<%= f.select :heard_about_us, ["", "News/Magzine", "Weibo/wechat/facebook", "HaiyanTour Website, Newsletter", "Conference", "Other"], {} %>
					<%= f.label :content %>
					<%= f.text_area :content %>
				</div>
				
				<div class="cbp-mc-submit-wrap">
					<%= f.submit "SUBMIT", :class => "cbp-mc-submit" %>
				</div>
			<% end %>
		</div>
	</div>
</body>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<%= stylesheet_link_tag "home.css" %>
	<!-- Page -->
	<div class="page">
		<div class="page-slides">
	    <img src="http://farm4.staticflickr.com/3649/3394771273_a9634a71a9_b.jpg">
	    <img src="http://farm4.staticflickr.com/3674/9414830088_e69653e8f8_b.jpg">
		</div>
		<div class="page-divider"></div>
		<div class="container">
			<h2 class="page-blurb">A town of <strong>plenty</strong>, a land of <strong>silk</strong>, a place will bring you <strong>incredible</strong> experiences.</h2>
			<hr class="line-divider"></hr>
		</div>
		<div id="columns">
			<div class="column what-we-have">
				<h3>What We Have</h3>
				<p>
					Here you can find a place for sight seeing, delicaious food, shopping and entertainment.
				</p>
				<%= link_to "Learn More", discovery_url, class:"anchored" %>
			</div>
			<div class="column local-weather">
				<h3>Local Weather</h3>
				<%= raw weather %>
			</div>
			<div class="column weibo-feeds">
				<h3>Follow Us</h3>
				<%= raw weibo %>
				<%= link_to "Read more weibos", "http://www.weibo.com/haiyantourism", class:"anchored" %>
				<div class="anchored">
							<a href="http://www.weibo.com/haiyantourism" class="weibo"></a>
				</div>
			</div>
		</div>
	</div>
</html>

app/views/pages/media.html.erb
<h1>COMING SOON ...</h1>

app/views/pages/news.html.erb
<h1>Pages#news</h1>
<p>Find me in app/views/pages/news.html.erb</p>

app/views/pages/story.html.erb
<!DOCTYPE html>
	<%= stylesheet_link_tag "home.css" %>
	<div class="page">
		<h1>Facts about Haiyan</h1>
		<p>Here you'll find everything you need to know to help you make the most of your visit to Haiyan. Learn about our history, culture, great food, art and spetacular natural landscapes.</p>
		<div>
			<img src="http://bestclipartblog.com/clipart-pics/square-clip-art-15.png">
			<h4>Key Facts</h4>
			<p>What is the weather is like, what you need to do when you need emergency serverices</p>
		</div>
		<div>
			<img src="http://bestclipartblog.com/clipart-pics/square-clip-art-15.png">
			<h4>History</h4>
			<p>Haiyan is one of the oldest town in China, as well as one of the youngest. Learn about our culture and history, and our most famous Haiyan</p>
		</div>
		<div>
			<img src="http://bestclipartblog.com/clipart-pics/square-clip-art-15.png">
			<h4>Haiyan's Landscapes</h4>
			<p>We have the unique scenic spot with hills, the sea and the lakes -- "Nanbei Lake"</p>
		</div>
	</div>
</html>